### ISSUE TITLE
Přístup pro mě

### ISSUE THREAD

**Issue by hroncok** [asgeirrr/prezencka#59]
Ahoj, v úterý budeme v NTK učit http://naucse.python.cz/2017/pyladies-praha-podzim-cznic/git/git-collaboration-2in1/

Mohl bych prosím dostat práva mergovat PR sem? Díky

**Comment by hroncok** [comment]
Případně asi stačí, pokud taková práva má @zuzejk.

**Comment by asgeirrr** [comment]
@hroncok žádný problém, dal jsem je oběma;)

**Comment by hroncok** [comment]
díky
